name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build the site with docfx"
    runs-on: ubuntu-latest
    steps:
      # Check out
      - uses: actions/checkout@v4
        name: Check out the code
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      - uses: "nunit/docfx-action@v2.10.0"
        name: Build with Docfx
        with:
          args: Documentation/docfx.json
      - name: zip site contents
        run: zip -r _site.zip Documentation/_site/
      - name: Archive site artifacts # Only way
        uses: actions/upload-artifact@v3
        with:
          name: siteArtifact
          path: _site.zip
  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifacts
        uses: actions/download-artifact@v3
        with:
          name: siteArtifact
      - name: unzip site contents
        run: unzip _site.zip
      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Documentation/_site
          publish_branch: gh-pages
          # hello_world_job:
          #   runs-on: ubuntu-latest
          #   name: Build Docs and scream it doest work
          #   steps:
          #   - uses: actions/checkout@v3
          #   # ...
          #   - uses: nikeee/docfx-action@v1.0.0
          #     name: Build Documentation
          #     with:
          #       args: Documentation/docfx.json
          #   - uses: peaceiris/actions-gh-pages@v3.6.1
          #     with:
          #       github_token: ${{ secrets.GITHUB_TOKEN }}
          #       publish_dir: ./docs
          #       force_orphan: true